### ISSUE TITLE
Error when running design.py example 

### ISSUE THREAD

**Issue by FyisFe** [broadinstitute/catch#42]
> design.py download:64320 -pl 75 -m 2 -l 60 -e 50 -o zika-probes.fasta --verbose

2022-02-23 17:02:05,101 - catch.utils.ncbi_neighbors [INFO] Creating a FASTA file for taxid 64320
2022-02-23 17:02:05,102 - catch.utils.ncbi_neighbors [INFO] Constructing a list of neighbors for taxid 64320
2022-02-23 17:03:56,248 - catch.utils.ncbi_neighbors [INFO] There are 1596 neighbors, 799 of which have unique accessions
Traceback (most recent call last):
  File "/Users/yfeng/opt/anaconda3/lib/python3.8/http/client.py", line 555, in _get_chunk_left
    chunk_left = self._read_next_chunk_size()
  File "/Users/yfeng/opt/anaconda3/lib/python3.8/http/client.py", line 522, in _read_next_chunk_size
    return int(line, 16)
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yfeng/opt/anaconda3/lib/python3.8/http/client.py", line 572, in _readall_chunked
    chunk_left = self._get_chunk_left()
  File "/Users/yfeng/opt/anaconda3/lib/python3.8/http/client.py", line 557, in _get_chunk_left
    raise IncompleteRead(b'')
http.client.IncompleteRead: IncompleteRead(0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yfeng/opt/anaconda3/bin/design.py", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/Users/yfeng/Desktop/catch/bin/design.py", line 856, in <module>
    main(args)
  File "/Users/yfeng/Desktop/catch/bin/design.py", line 66, in main
    ds_fasta_tf = ncbi_neighbors.construct_fasta_for_taxid(taxid,
  File "/Users/yfeng/Desktop/catch/catch/utils/ncbi_neighbors.py", line 465, in construct_fasta_for_taxid
    seqs_tf = fetch_fastas(acc_to_fetch)
  File "/Users/yfeng/Desktop/catch/catch/utils/ncbi_neighbors.py", line 207, in fetch_fastas
    raw_data = r.read()
  File "/Users/yfeng/opt/anaconda3/lib/python3.8/http/client.py", line 465, in read
    return self._readall_chunked()
  File "/Users/yfeng/opt/anaconda3/lib/python3.8/http/client.py", line 579, in _readall_chunked
    raise IncompleteRead(b''.join(value))
http.client.IncompleteRead: IncompleteRead(536576 bytes read)

**Comment by FyisFe** [comment]
Exactly, I used another network then it worked well. Thank you so much for your kindness😄!
