### ISSUE TITLE
Error running design.py: unexpected keyword argument 'avoided_genomes'

### ISSUE THREAD

**Issue by MGeraerts** [broadinstitute/catch#55]
Dear Dr. Metsky,

I contact you regarding the software CATCH that you developed, which is a very interesting tool for me to use on my own data.
I have installed the software but when I run the example as written in Github, I get the following output and error message:

design.py download:64320 -pl 75 -m 2 -l 60 -e 50 -o zika-probes.fasta --verbose

2023-08-08 14:14:53,897 - catch.utils.ncbi_neighbors [INFO] Creating a FASTA file for taxid 64320
2023-08-08 14:14:53,898 - catch.utils.ncbi_neighbors [INFO] Constructing a list of neighbors for taxid 64320
2023-08-08 14:14:59,166 - catch.utils.ncbi_neighbors [INFO] There are 1602 neighbors, 802 of which have unique accessions
2023-08-08 14:15:16,135 - catch.utils.seq_io [INFO] Reading fasta file /tmp/tmpcnemrqnp
Traceback (most recent call last):
  File "/data/antwerpen/209/vsc20911/Miniconda3/bin/catch/bin/design.py", line 958, in <module>
    main(args)
  File "/data/antwerpen/209/vsc20911/Miniconda3/bin/catch/bin/design.py", line 325, in main
    scf = set_cover_filter.SetCoverFilter(
TypeError: __init__() got an unexpected keyword argument 'avoided_genomes'

Is there a way to solve this error?

Thank you in advance for your response!

Kind regards,
MGeraerts

**Comment by haydenm** [comment]
Unfortunately it's not obvious to me what is causing that error, and I'm not able to reproduce it. In an older version of CATCH (>1 year ago), `set_cover_filter.SetCoverFilter.__init__()` did not have the keyword argument `avoided_genomes`. Also, the miniconda path—in particular, the part with `...Miniconda3/bin/catch/...` looks unusual to me. Together, these make me wonder if an older version of CATCH could have once been installed on this machine and something weird happened when re-installing it, or if something unusual happened when installing it the first time.

Could you try installing CATCH from scratch inside a new, separate conda environment? The README describes how, but briefly it would take running:
```
> conda create -n catch-env python=3.8
> conda activate catch-env
> conda install -c bioconda catch
```
and then running the `design.py` command as you did. Let me know if that works. I would be surprised if installing it from scratch, in an isolated environment, led to that same error message.

**Comment by haydenm** [comment]
Great—I'm glad that worked!
