### ISSUE TITLE
Problem install Catch

### ISSUE THREAD

**Issue by OrsonMM** [broadinstitute/catch#56]
Dear team Catch 

I have this error installing catch 

catch$ pip install -e .

Obtaining file:///home/ins-bio/programas/catch
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [62 lines of output]
      /home/ins-bio/programas/anaconda_install/lib/python3.11/site-packages/setuptools/dist.py:520: SetuptoolsDeprecationWarning: Invalid version: 'v1.5.1-17-g9c4696c2'.
      !!

              ********************************************************************************
              The version specified is not a valid version according to PEP 440.
              This may not work as expected with newer versions of
              setuptools, pip, and PyPI.

              This deprecation is overdue, please update your project and remove deprecated
              calls to avoid build errors in the future.

              See https://peps.python.org/pep-0440/ for details.
              ********************************************************************************

      !!
        self._validate_version(self.metadata.version)
      running egg_info
      /home/ins-bio/programas/anaconda_install/lib/python3.11/site-packages/setuptools/command/egg_info.py:131: SetuptoolsDeprecationWarning: Invalid version: 'v1.5.1-17-g9c4696c2'.
      !!

              ********************************************************************************
              Version 'v1.5.1-17-g9c4696c2' is not valid according to PEP 440.

              Please make sure to specify a valid version for your package.
              Also note that future releases of setuptools may halt the build process
              if an invalid version is given.

              This deprecation is overdue, please update your project and remove deprecated
              calls to avoid build errors in the future.

              See https://peps.python.org/pep-0440/ for details.
              ********************************************************************************

      !!
        return _normalization.best_effort_version(tagged)
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/ins-bio/programas/catch/setup.py", line 11, in <module>
          setup(name='catch',
        File "/home/ins-bio/programas/anaconda_install/lib/python3.11/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/ins-bio/programas/anaconda_install/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/home/ins-bio/programas/anaconda_install/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/home/ins-bio/programas/anaconda_install/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/home/ins-bio/programas/anaconda_install/lib/python3.11/site-packages/setuptools/dist.py", line 1244, in run_command
          super().run_command(command)
        File "/home/ins-bio/programas/anaconda_install/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.ensure_finalized()
        File "/home/ins-bio/programas/anaconda_install/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 111, in ensure_finalized
          self.finalize_options()
        File "/home/ins-bio/programas/anaconda_install/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 219, in finalize_options
          parsed_version = packaging.version.Version(self.egg_version)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/ins-bio/programas/anaconda_install/lib/python3.11/site-packages/setuptools/_vendor/packaging/version.py", line 197, in __init__
          raise InvalidVersion(f"Invalid version: '{version}'")
      setuptools.extern.packaging.version.InvalidVersion: Invalid version: 'v1.5.1-17-g9c4696c2'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by haydenm** [comment]
Thank you for flagging this. It seems to be a widely-encountered issue with newer versions of setuptools that enforce a particular version format, e.g., see https://github.com/pypa/setuptools/issues/3772. CATCH did not follow that version format.

I reproduced your issue and made a fix, c36080d, which resolves it for me. Please try updating CATCH, e.g., by running `git pull`, before installing it again. Let me know if you still encounter the issue.

**Comment by OrsonMM** [comment]
Thanks 
 
It works 

![image](https://github.com/broadinstitute/catch/assets/12600107/19134e83-11f6-4bdb-99eb-fbf0fcb89cab)
